baseurl = "http://jyu213.github.io/"
title = "前端杂货铺"
theme = "elves"
hasCJKLanguage = true

[params]
    Author = "见见"
    ## Logo = "/images/ava.jpeg"
    DateForm = "2006-01-02"
    Comments = true
    GoogleAnalyticsUserID = "UA-41493088-2"
    ShowRelatedPost = false
    SyntaxHighlightTheme = "solarized_dark.min.css"
    CopyrightHTML = ""

[Indexes]
    tag = "tags"

[permalinks]
    post = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "翻译"
    url = "/categories/translate"
[[menu.main]]
    name = "JS"
    url = "/categories/js"
[[menu.main]]
    name = "CSS"
    url = "/categories/css"
[[menu.main]]
    name = "首页"
    url = "/"
